### ISSUE TITLE
Best way to get "parts" of a selector

### ISSUE THREAD

**Issue by HerrZatacke** [lachlanmcdonald/postcss-filter-rules#9]
In the callback I receive the two values `selector` and `parts`
In my case I'd like to determine the "part of a part" as follows:  

with the selector `.keep.otherclass[some-attr]`
I receive the parts as `[ '.keep.otherclass[some-attr]' ]`

So basically I still have to implement my own parsing of the parts via a regex.
What would be cool would be a third parameter which for the above case would give us an array like
`[ '.keep', '.otherclass', '[some-attr]' ]`

Currently I'm parsing the `parts` myself like this, but I wonder if this could/should be included into the plugin itself?:

``` javascript

const keeps = ['.selectors', '.to', '.keep'];

const tokenize = (selector) => {
  const splits = /[ :[.#]+/gi;
  let indices = [];
  let match;

  do {
    match = splits.exec(selector);
    if (match) {
      indices.push(match.index);
    }
  } while (match);

  return indices.map((index, indexIndex) => {
    return selector.substring(index, indices[indexIndex + 1])
  });
};

const result = postcss(filterRules({
  filter: (selector, parts) => {
    const tokenizedParts = parts.map(tokenize).flat(); // here the transformation happens
    const intersection = tokenizedParts.filter(part => keeps.includes(part));
    return intersection.length > 0;
  }
})).process(...);
```

**Comment by lachlanmcdonald** [comment]
Hi @HerrZatacke; I've published a new version of the plugin which lets you specific your own callback function to generate the `parts` argument that is passed to the results.

You can use this gist to separate the `parts` as you desire: https://gist.github.com/lachlanmcdonald/37bf3c1c7e244dd6fc9817e769af4897
